### PR TITLE
clean test logs by removing irrelevant messages from electron

### PR DESCRIPTION
**Pull request by StevenLove**

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
My concern is hijacking stdout/stderr may have unseen complexity. 
Is there any way to suppress the vscode's error?

**Comment by StevenLove** [comment]
I agree that modifying process.stdout.write and process.stderr.write may be a kludge.

I don't know how to suppress vscode's error messages from showing up in the terminal but I agree that would be the best solution.

What do you think of this alternative solution?
Let the code run as normal and pipe the output into grep to remove the offending lines. I can modify `package.json`'s `test` script to do this easily

I preferred the approach that I submitted because it allows us to clearly document the reasoning behind why certain lines should be filtered out. I looked for best practices but could not find any for this scenario which I thought would be quite common. My guess is that maybe the issue is easily resolved when using a logging framework and that's why people are not clamoring about how to properly remove irrelevant third party logs.

**Comment by StevenLove** [comment]
Good find! I didn’t see that vscode-test issue. For clarity, I’ll point out that I was advocating removing just a few very specific messages and not for hiding all of stderr. But I can see that it still could cause some confusion to modify the logs in any way

**Comment by HerringtonDarkholme** [comment]
thanks for the understanding. I'm closing this now.

**Pull request closed without merging**
