### PR TITLE
Speed up integration test by 2 seconds

### PR DESCRIPTION
**Pull request by StevenLove**
Speed up the integration test from 12s to 10s
by directly launching the extension host with the test fixture directory and file already open. Otherwise the extension host opens and then reopens itself with the test fixture directory and file open.

This replaces the `activate` function from `src/test/utils.ts`
``` typescript
export async function activate() {
  // The extensionId is `publisher.name` from package.json
  const ext = vscode.extensions.getExtension('ast-grep.ast-grep-vscode')!
  const fixtureFolderUri = vscode.Uri.file(
    path.resolve(__dirname, '../../fixture')
  )
  await ext.activate()
  try {
    // open ast-grep project to locate sgconfig.yml
    await vscode.commands.executeCommand('vscode.openFolder', fixtureFolderUri)
    doc = await vscode.workspace.openTextDocument(getDocUri('test.ts'))
    editor = await vscode.window.showTextDocument(doc)
    // enforce unix line endings, otherwise tests fail on windows
    await editor.edit(builder => {
      builder.setEndOfLine(vscode.EndOfLine.LF)
    })
    await sleep(1500) // Wait for server activation
  } catch (e) {
    console.error(e)
  }
}
```

modifying `runTest.mjs`, we can replace the calls to `vscode.workspace.executeCommand`, `vscode.workspace.openTextDocument`, and `vscode.window.showTextDocument`
``` javascript
await runTests({
      extensionDevelopmentPath,
      extensionTestsPath,
      launchArgs: [
        '--disable-extensions',
        fixtureDirectoryPath,
        initialFilePath
      ]
    })
```
And we don't need to call `activate` on the extension because `package.json` already has 
``` json
  "activationEvents": [
    "onStartupFinished"
  ],
```
And the last piece is the line endings which can be handled by adding a setting to `.vscode/settings.json`
``` json
  "files.eol": "\n"
```

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 2df91c7d1a92684739f8b885f909825cebe69645.  | 
|--------|--------|

### Summary:
This PR optimizes the integration test by directly launching the extension host with the test fixture directory and file already open, eliminating the need for the `activate` function and handling line endings via `.vscode/settings.json`.

**Key points**:
- Removed the `activate` function from `src/test/utils.ts`.
- Modified `runTest.mjs` to replace calls to `vscode.workspace.executeCommand`, `vscode.workspace.openTextDocument`, and `vscode.window.showTextDocument`.
- Removed the need to call `activate` on the extension due to `onStartupFinished` in `activationEvents` of `package.json`.
- Handled line endings by adding a setting to `.vscode/settings.json`.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by StevenLove** [comment]
I see that this failed the windows check which I was fearing. The failure came from getting 0 issues instead of the expected 3, so I believe this error isn't attributable to the unix EOL issue. Does this strike you as another timing issue that windows just needs some more time?

**Comment by HerringtonDarkholme** [comment]
@StevenLove can you give windows a look? It still fails after multiple times.

**Comment by HerringtonDarkholme** [comment]
@StevenLove would you like to give this one more look?

**Comment by StevenLove** [comment]
From a git perspective, I found it easier to issue a new PR. I think because ~60 commits had occurred since I submitted this PR that made the rebase more difficult. After submitting the other PR I see it is annoying to have these two PRs. See [the newer PR replacing this one](https://github.com/ast-grep/ast-grep-vscode/pull/161)

**Pull request closed without merging**
